export const mockData = [
    {
      "login": "antonio06",
      "id": 14540103,
      "node_id": "MDQ6VXNlcjE0NTQwMTAz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/14540103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/antonio06",
      "html_url": "https://github.com/antonio06",
      "followers_url": "https://api.github.com/users/antonio06/followers",
      "following_url": "https://api.github.com/users/antonio06/following{/other_user}",
      "gists_url": "https://api.github.com/users/antonio06/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/antonio06/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/antonio06/subscriptions",
      "organizations_url": "https://api.github.com/users/antonio06/orgs",
      "repos_url": "https://api.github.com/users/antonio06/repos",
      "events_url": "https://api.github.com/users/antonio06/events{/privacy}",
      "received_events_url": "https://api.github.com/users/antonio06/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "brauliodiez",
      "id": 1457912,
      "node_id": "MDQ6VXNlcjE0NTc5MTI=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1457912?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/brauliodiez",
      "html_url": "https://github.com/brauliodiez",
      "followers_url": "https://api.github.com/users/brauliodiez/followers",
      "following_url": "https://api.github.com/users/brauliodiez/following{/other_user}",
      "gists_url": "https://api.github.com/users/brauliodiez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/brauliodiez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/brauliodiez/subscriptions",
      "organizations_url": "https://api.github.com/users/brauliodiez/orgs",
      "repos_url": "https://api.github.com/users/brauliodiez/repos",
      "events_url": "https://api.github.com/users/brauliodiez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/brauliodiez/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "crsanti",
      "id": 13205689,
      "node_id": "MDQ6VXNlcjEzMjA1Njg5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/13205689?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/crsanti",
      "html_url": "https://github.com/crsanti",
      "followers_url": "https://api.github.com/users/crsanti/followers",
      "following_url": "https://api.github.com/users/crsanti/following{/other_user}",
      "gists_url": "https://api.github.com/users/crsanti/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/crsanti/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/crsanti/subscriptions",
      "organizations_url": "https://api.github.com/users/crsanti/orgs",
      "repos_url": "https://api.github.com/users/crsanti/repos",
      "events_url": "https://api.github.com/users/crsanti/events{/privacy}",
      "received_events_url": "https://api.github.com/users/crsanti/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "fjcalzado",
      "id": 24454225,
      "node_id": "MDQ6VXNlcjI0NDU0MjI1",
      "avatar_url": "https://avatars0.githubusercontent.com/u/24454225?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fjcalzado",
      "html_url": "https://github.com/fjcalzado",
      "followers_url": "https://api.github.com/users/fjcalzado/followers",
      "following_url": "https://api.github.com/users/fjcalzado/following{/other_user}",
      "gists_url": "https://api.github.com/users/fjcalzado/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fjcalzado/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fjcalzado/subscriptions",
      "organizations_url": "https://api.github.com/users/fjcalzado/orgs",
      "repos_url": "https://api.github.com/users/fjcalzado/repos",
      "events_url": "https://api.github.com/users/fjcalzado/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fjcalzado/received_events",
      "type": "User",
      "site_admin": false
    }
]